# Travis CI build file for KituraKit.

branches:
  only:
    - pod

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required

before_install:
  - git clone https://github.com/IBM-Swift/Package-Builder.git

script:
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR

jobs: 
  include: 
     - stage: Releases
       script: ci/release.sh
